name: HACS Action

on:
  push:
  pull_request:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"